config/routes.rb
Rails.application.routes.draw do
  # This part of Rails is criminally underdeveloped, and I want to help but I
  # am not able to.

  root    'cardiograms#index'

  # Login
  get     '/login',               to: 'sessions#new'
  post    '/login',               to: 'sessions#create'
  delete  '/logout',              to: 'sessions#destroy'

  # Pulses
  get     '/cdg/:name/pls',       to: 'pulses#index',       as: 'pulses'
  get     '/cdg/:name/pls/new',   to: 'pulses#new',         as: 'new_pulse'
  post    '/cdg/:name/pls',       to: 'pulses#create'
  delete  '/cdg/:name/:version',  to: 'pulses#destroy'

  # Cardiograms
  get     '/cdgs',                to: 'cardiograms#index',  as: 'cardiograms'
  post    '/cdgs',                to: 'cardiograms#create'
  get     '/cdgs/new',            to: 'cardiograms#new',    as: 'new_cardiogram'

  get     '/cdg/:name',           to: 'cardiograms#show',   as: 'cardiogram'
  patch   '/cdg/:name',           to: 'cardiograms#update'
  delete  '/cdg/:name',           to: 'cardiograms#destroy',as: 'delete_cardiogram'
  get     '/cdg/:name/:version',  to: 'cardiograms#show',   as: 'cardiogram_version'

  get     '/cdg/:name/edit',      to: 'cardiograms#edit',   as: 'edit_cardiogram'

  # Users
  get     '/users',               to: 'users#index',        as: 'users'
  post    '/users',               to: 'users#create'
  get     '/users/new',           to: 'users#new',          as: 'new_user'

  get     '/user/:name',          to: 'users#show',         as: 'user'
  delete  '/user/:name',          to: 'users#destroy',      as: 'delete_user'

  get     '/user/:name/edit',     to: 'users#edit',         as: 'edit_user'
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true,
                       uniqueness: true

  validates :email, presence: true,
                    format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
                              message: 'Invalid email.'},
                    length: { maximum: 256 },
                    uniqueness: true

  validates :name,  presence: true,
                    length: { maximum: 64 }

  validates :password, confirmation: true
  has_secure_password

  has_many :cardiograms, dependent: :destroy

  def to_param
    username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find_by_username(params[:name])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :name, :dob, :password, :password_confirmation, :username)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :dob, "DOB" %>
    <%= form.date_select :dob, start_year: Date.today.year - 80, end_year: Date.today.year, default: Date.today %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>DOB</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.dob %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @user.dob %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>