config/routes.rb
Rails.application.routes.draw do
  # This part of Rails is criminally underdeveloped, and I want to help but I
  # am not able to.

  root    'cardiograms#index'

  # Login
  get     '/login',               to: 'sessions#new'
  post    '/login',               to: 'sessions#create'
  delete  '/logout',              to: 'sessions#destroy'

  # Pulses
  get     '/cdg/:name/pls',       to: 'pulses#index',       as: 'pulses'
  get     '/cdg/:name/pls/new',   to: 'pulses#new',         as: 'new_pulse'
  post    '/cdg/:name/pls',       to: 'pulses#create'
  delete  '/cdg/:name/:version',  to: 'pulses#destroy'

  # Cardiograms
  get     '/cdgs',                to: 'cardiograms#index',  as: 'cardiograms'
  post    '/cdgs',                to: 'cardiograms#create'
  get     '/cdgs/new',            to: 'cardiograms#new',    as: 'new_cardiogram'

  get     '/cdg/:name',           to: 'cardiograms#show',   as: 'cardiogram'
  patch   '/cdg/:name',           to: 'cardiograms#update'
  delete  '/cdg/:name',           to: 'cardiograms#destroy',as: 'delete_cardiogram'
  get     '/cdg/:name/:version',  to: 'cardiograms#show',   as: 'cardiogram_version'

  get     '/cdg/:name/edit',      to: 'cardiograms#edit',   as: 'edit_cardiogram'

  # Users
  get     '/users',               to: 'users#index',        as: 'users'
  post    '/users',               to: 'users#create'
  get     '/users/new',           to: 'users#new',          as: 'new_user'

  get     '/user/:name',          to: 'users#show',         as: 'user'
  delete  '/user/:name',          to: 'users#destroy',      as: 'delete_user'

  get     '/user/:name/edit',     to: 'users#edit',         as: 'edit_user'
end

app/models/cardiogram.rb
class Cardiogram < ApplicationRecord
  has_many :pulses, dependent: :destroy

  belongs_to :user

  def to_param
    name
  end
end

app/controllers/cardiograms_controller.rb
class CardiogramsController < ApplicationController
  before_action :set_cardiogram, only: [:show, :edit, :update, :destroy]

  # GET /cdgs
  # GET /cdgs.json
  def index
    @cardiograms = Cardiogram.all.sort
  end

  # GET /cdg/:name
  # GET /cdg/:name.json
  # GET /cdg/:name/:version
  # GET /cdg/:name/:version.json
  def show
    @cardiogram = Cardiogram.find_by_name(params[:name])
  end

  # GET /cdgs/new
  def new
    @cardiogram = Cardiogram.new
  end

  # GET /cdg/:name/edit
  def edit
  end

  # POST /cdgs
  # POST /cdgs.json
  def create
    @cardiogram = Cardiogram.new(cardiogram_params)

    respond_to do |format|
      if @cardiogram.save
        format.html { redirect_to @cardiogram, notice: 'Cardiogram was successfully created.' }
        format.json { render :show, status: :created, location: @cardiogram }
      else
        format.html { render :new }
        format.json { render json: @cardiogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cdg/:name
  # PATCH/PUT /cdg/:name.json
  def update
    respond_to do |format|
      if @cardiogram.update(cardiogram_params)
        format.html { redirect_to @cardiogram, notice: 'Cardiogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardiogram }
      else
        format.html { render :edit }
        format.json { render json: @cardiogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cdg/:name
  # DELETE /cdg/:name.json
  def destroy
    if current_user == @cardiogram.user
      @cardiogram.destroy

      respond_to do |format|
        format.html { redirect_to cardiograms_url, notice: 'Cardiogram was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @cardiogram, notice: 'Cardiogram can only be deleted by owner.'}
        format.json { render json: @cardiogram.errors, status: :forbidden }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cardiogram
    @cardiogram = Cardiogram.find_by_name params[:name]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cardiogram_params
    params.require(:cardiogram).permit(:name, :desc, :authors, :user_id)
  end
end

app/helpers/cardiograms_helper.rb
module CardiogramsHelper
end

app/views/cardiograms/_form.html.erb
<%= form_with(model: cardiogram, local: true) do |form| %>
  <% if cardiogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cardiogram.errors.count, "error") %> prohibited this cardiogram from being saved:</h2>

      <ul>
      <% cardiogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :authors %>
    <%= form.text_field :authors %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cardiograms/edit.html.erb
<h1>Editing Cardiogram</h1>

<%= render 'form', cardiogram: @cardiogram %>

app/views/cardiograms/index.html.erb
<p id="notice"><%= notice %></p>

<div class="cdgs">
  <% @cardiograms.each do |cdg| %>
    <div class="cdg">
      <div class="name">
        <a href="<%= cardiogram_path cdg %>"><%= cdg.name %></a>
      </div>
      <div class="description">
        <%= cdg.desc %>
      </div>
      <div class="user">
        <a href="<%= user_path cdg.user %>"><%= cdg.user.name %></a>
      </div>
      <div class="version">
        <%= cdg.latest_version %>
      </div>
      <div class="downloads">
        100 <!-- TODO: keep track of dls -->
      </div>
      <div class="graphic">
        <!-- image: each letter has a y value, each index has an x value, all
             package names must be unique, therefore each cardiogram has a
             unique graphic -->
      </div>
    </div>
  <% end %>
</div>

app/views/cardiograms/new.html.erb
<h1>Create Cardiogram</h1>

<%= render 'form', cardiogram: @cardiogram %>

<%= link_to 'Back', cardiograms_path %>

app/views/cardiograms/show.html.erb
<div class="show">
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% else %>
    <div id="notice"></div>
  <% end %>

  <!--
    The borders are misaligned by design.
    Honestly.
      .meta { margin-top: -1mm; }
    would solve it, but it looks weird.
  -->

  <div class="readme">
    <h1>READMEs not implemented yet</h1>
    <p>sue me</p>
  </div>

  <div class="meta">
    <% if logged_in? %>
    <div class="tools"> <!--font-family: ulf400 ??-->
        <div class="edit"> <!--Yellow (complementary (3))?-->
          <a href="<%= edit_cardiogram_path @cardiogram %>">
            <!--&#128393;-->
            EDIT
          </a>
        </div>
        <div class="delete">
          <!--&#128393;-->
            <%= link_to  'DELETE', delete_cardiogram_path, method: :delete %>
        </div> <!--Red (not $main-colour-or-whatever-0)-->
        <div class="move">
          <!--&#128666;-->
          MOVE
        </div> <!--Blue (complementary (3))?-->
        <div class="pulse">
          <a href="<%= new_pulse_path %>">
            PULSE
          </a>
        </div>
    </div>
    <% end %>

    <div class="version">
      <h4>Version</h4>
      <!-- params[:version] || -->
      <%= @cardiogram.latest_version %> (latest)
    </div>

    <div class="install">
      <h4>Install</h4>
      <code>bpm add <%= @cardiogram.name %></code>
    </div>

    <div class="desc">
      <h4>Description</h4>
      <%= @cardiogram.desc %>
    </div>

    <% if @cardiogram.repo %>
      <div class="repo">
        <h4>Source</h4>
        <!-- TODO: Add host-specific badges (github, gitlab, etc.) -->
        <a href="<%= @cardiogram.repo %>"><%= @cardiogram.repo %></a>
      </div>
    <% end %>

    <div class="authors">
      <h4>Authors</h4>
      <!-- <<= author_helper @cardiogram.authors >> -->
      <%= @cardiogram.authors %>
    </div>
  </div>
</div>